backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  - name: "horses"
    label: "馬プロフィール"
    folder: "src/horses"
    create: true
    slug: "{{id}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "名前", name: "name", widget: "string" }
      - { label: "誕生日", name: "birthday", widget: "date", format: "YYYY/MM/DD" }
      - { label: "画像", name: "image", widget: "image" }
      - { label: "説明", name: "description", widget: "text" }

  - name: "posts"
    label: "タイムライン投稿"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日付", name: "date", widget: "datetime" }
      - { label: "馬ID", name: "horse_id", widget: "select", options: ["hime", "kokeshi", "momo"] }
      - { label: "本文", name: "body", widget: "markdown" }
      - label: "画像"
        name: "images"
        widget: "list"
        field:
          { label: "画像", name: "image", widget: "image" }
